---
apiVersion: v1
kind: Service
metadata:
  labels:
    release: {{ .Release.Name }}
    app: {{ include "curve-csi.name" . }}-controllerplugin
  name: {{ include "curve-csi.name" . }}-controllerplugin
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ include "curve-csi.name" . }}-controllerplugin
  type: ClusterIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "curve-csi.name" . }}-controllerplugin
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: csi-curve-plugin-provisioner
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "curve-csi.name" . }}-controllerplugin
  template:
    metadata:
      labels:
        app: {{ include "curve-csi.name" . }}-controllerplugin
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "curve-csi.name" . }}-controllerplugin
            topologyKey: kubernetes.io/hostname
      serviceAccount: curve-csi-provisioner
      containers:
      - name: csi-provisioner
        image: "{{ .Values.controllerplugin.provisioner.image.repository }}:{{ .Values.controllerplugin.provisioner.image.tag }}"
        imagePullPolicy: {{ .Values.controllerplugin.provisioner.image.pullPolicy }}
        args:
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        - "--timeout=150s"
        - "--retry-interval-start=500ms"
        env:
        - name: ADDRESS
          value: unix:///csi/csi-provisioner.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        resources:
{{ toYaml .Values.controllerplugin.provisioner.resources | indent 10 }}
      - name: csi-attacher
        image: "{{ .Values.controllerplugin.attacher.image.repository }}:{{ .Values.controllerplugin.attacher.image.tag }}"
        imagePullPolicy: {{ .Values.controllerplugin.attacher.image.pullPolicy }}
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /csi/csi-provisioner.sock
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        resources:
{{ toYaml .Values.controllerplugin.attacher.resources | indent 10 }}
      - name: csi-curveplugin
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        image: "{{ .Values.controllerplugin.plugin.image.repository }}:{{ .Values.controllerplugin.plugin.image.tag }}"
        imagePullPolicy: {{ .Values.controllerplugin.plugin.image.pullPolicy }}
        args:
        - --endpoint=$(CSI_ENDPOINT)
        - --drivername=curve.csi.netease.com
        - --nodeid=$(NODE_ID)
{{- if .Values.controllerplugin.debug.enabled }}
        - "--debug-port={{ .Values.controllerplugin.debug.port }}"
{{- end }}
        - --controller-server=true
{{- if .Values.controllerplugin.logToFile.enabled }}
        - --logtostderr=false
        - --log_dir=/var/log/csi-curveplugin
{{- end }}
        - -v=4
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///csi/csi-provisioner.sock
        resources:
{{ toYaml .Values.controllerplugin.attacher.resources | indent 10 }}
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - mountPath: /etc/localtime
          name: localtime
{{- if .Values.controllerplugin.logToFile.enabled }}
        - mountPath: /var/log/csi-curveplugin
          name: log
{{- end }}
      volumes:
      - name: socket-dir
        emptyDir:
          medium: Memory
      - hostPath:
          path: /etc/localtime
        name: localtime
{{- if .Values.controllerplugin.logToFile.enabled }}
      - hostPath:
          path: {{ .Values.controllerplugin.logToFile.hostDir }}
        name: log
{{- end -}}
{{- if .Values.controllerplugin.affinity }}
      affinity:
{{ toYaml .Values.controllerplugin.affinity . | indent 8 -}}
{{- end -}}
{{- if .Values.controllerplugin.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.controllerplugin.nodeSelector | indent 8 -}}
{{- end -}}
{{- if .Values.controllerplugin.tolerations }}
      tolerations:
{{ toYaml .Values.controllerplugin.tolerations | indent 8 -}}
{{- end -}}
