---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: curve-pvc-restore
spec:
  storageClassName: curve
  dataSource:
    name: curve-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi