---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: curve-pvc-clone
spec:
  storageClassName: curve
  dataSource:
    name: curve-test-pvc
    kind: PersistentVolumeClaim
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi